UIAPI/app/apirest/urls.py
from django.contrib import admin
from django.urls import include, path
from rest_framework import routers, serializers, viewsets

urlpatterns = [
    path('', include('firstapp.urls'))
]

UIAPI/app/firstapp/urls.py
from django.urls import path

from . import views

app_name="firstapp"

urlpatterns = [
    path('',views.vista,name='vista'),
    path('dogs',views.dogs,name='dogs'),
    path('dog/add',views.dogsAdd,name='dogsAdd'),
    path('dog/delete',views.dogsDelete,name='dogsdelete'),
    path('dog/get',views.dogsGet,name='dogsGet'),
    path('dog/get/<int:dogid>',views.dogsGetId,name='dogsGetId'),
    path('dog/update/<int:dogid>',views.dogsUpdate,name='dogsUpdate'),
    path('types',views.types,name='types'),
    path('videogames',views.videogames,name='videogames'),
    path('videogame/add',views.videogamesAdd,name='videogamesAdd'),
    path('videogame/delete/<int:videogameid>',views.videogamesDelete,name='videogamesdelete'),
    path('videogame/get',views.videogamesGet,name='videogamesGet'),
    path('videogame/get/<int:videogameid>',views.videogamesGetId,name='videogamesGetId'),
    path('videogame/update/<int:videogameid>',views.videogamesUpdate,name='videogamesUpdate'),
    path('rating',views.rating,name='rating'),
    path('rating/add',views.ratingAdd,name='ratingAdd'),
    path('rating/delete',views.ratingDelete,name='ratingdelete'),
    path('add',views.add,name='add'),
    path('delete/<int:videogameid>/<str:videogame>',views.delete,name='delete'),
    path('update/<int:videogameid>',views.update,name='update'),

]

UIAPI/app/firstapp/models.py
from django.db import models

# Create your models here.

class Dogs(models.Model):
    name = models.CharField(max_length=250, blank=True, null=True)
    type_id = models.IntegerField(blank=True, null=True)
    color = models.CharField(max_length=250, blank=True, null=True)
    size = models.CharField(max_length=50, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'dogs'


class Types(models.Model):
    name = models.CharField(max_length=250, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'types'

class DogFoods(models.Model):
    name = models.CharField(max_length=250, blank=True, null=True)
    brand = models.CharField(max_length=250, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'dog_foods'


class Videogames(models.Model):
    name = models.CharField(max_length=50, blank=True, null=True)
    genre = models.CharField(max_length=50, blank=True, null=True)
    rating_id = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'videogames'


class Rating(models.Model):
    esrb = models.CharField(max_length=50, blank=True, null=True)
    pegi = models.CharField(max_length=50, blank=True, null=True)
    cero = models.CharField(max_length=50, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'rating'

UIAPI/app/firstapp/views.py
# Create your views here.
#IMPORT models

#IMPORT LIBRARIRES/FUNCTIONS
from django.shortcuts import render , HttpResponse, redirect
from django.http import JsonResponse
import json
import requests
#IMPORT DJANGO PASSWORD HASH GENERATOR AND COMPARE
from django.contrib.auth.hashers import make_password, check_password
from .models import Dogs,Types, Videogames, Rating
from django import forms

#check_password(noHashPassword,HashedPassword) this funcion validate if the password match to the hash

#def vista(request):
#    return render(request,'clase.html')



class VideogameForm(forms.ModelForm):
    class Meta:
        model = Videogames #model es igual al modelo del archivo models.py
        fields = [
            'name',
            'genre',
            'rating_id',
            
        ]
        labels = { 
            'name' : 'Nombre', 
            'genre' : 'Genero',
            'rating_id' : 'Rating id',
            
        }
        widgets = {
            'name' : forms.TextInput(attrs={'required': True, 'class': 'form-control'}), #Para validar los campos del form
            'genre' : forms.TextInput(attrs={'required': True, 'class': 'form-control'}),
            'rating_id' : forms.NumberInput(attrs={'required': True, 'class': 'form-control'})
        }

def vista(request):


    
    if request.method == 'GET':

        responseData = {}
        responseData['success'] = 'true'
        responseData['data'] = list(Videogames.objects.all().values())
      
        cuantos = len(responseData['data']);
        return render(request, 'clase.html', {'cuantos': cuantos , "videogames": responseData })

    else:

        responseData = {}
        responseData['success'] = 'false'
        responseData['mesage'] = 'Wrong Method'

        cuantos = len(responseData['data']);
        return render(request, 'clase.html', {'cuantos': cuantos , "videogames": responseData })




def dogs(request):

    if request.method == 'GET':

        apikey = request.headers.get('api_key')
        apikey = "33390d09esdioewu0qe0uqu0"
        if apikey is not None:

            if apikey != "33390d09esdioewu0qe0uqu0":
                responseData = {}
                responseData['success'] = 'false'
                responseData['message'] = 'API KEY NOT VALID'
                return JsonResponse(responseData, status=400)

            responseData = {}
            responseData['success'] = 'true'
            responseData['key'] = apikey
            responseData['data'] = list(Dogs.objects.all().values())
            return JsonResponse(responseData, status=200)

        responseData = {}
        responseData['success'] = 'false'
        responseData['message'] = 'No api Key'
        return JsonResponse(responseData, status=400)

    else:

        responseData = {}
        responseData['success'] = 'false'
        responseData['mesage'] = 'Wrong Method'
        return JsonResponse(responseData, status=400)


def dogsAdd(request):

    if request.method == 'POST':

        try:
            json_object = json.loads(request.body)
            newDog = Dogs(name=json_object['dog_name'], type_id=json_object['dog_type_id'], color=json_object['dog_color'], size= json_object['dog_size'])
            #INSERT INTO dogs (name, type_id,color,size) values ('Solovino',4,'black','big')
            newDog.save()
            responseData = {}
            responseData['success'] = 'true'
            responseData['message'] = 'Dog inserted'
            return JsonResponse(responseData, status=200)
        except ValueError as e:
            responseData = {}
            responseData['success'] = 'false'
            responseData['message'] = 'Invalid Json'
            return JsonResponse(responseData, status=400)

    else:

        responseData = {}
        responseData['success'] = 'false'
        responseData['mesage'] = 'Wrong Method'
        return JsonResponse(responseData, status=400)

def dogsDelete(request):

    if request.method == 'DELETE':

        try:
            json_object = json.loads(request.body)
            try:
                one_entry = Dogs.objects.get(id=json_object["dog_id"])
            except:
                responseData = {}
                responseData['success'] = 'false'
                responseData['message'] = 'The dog_id its not valid'
                return JsonResponse(responseData, status=400)
            Dogs.objects.filter(id=json_object["dog_id"]).delete()
            responseData = {}
            responseData['success'] = 'true'
            responseData['message'] = 'The dog has been deleted'
            return JsonResponse(responseData, status=200)
        except ValueError as e:
            responseData = {}
            responseData['success'] = 'false'
            responseData['data'] = 'Invalid Json'
            return JsonResponse(responseData, status=400)
    else:

        responseData = {}
        responseData['success'] = 'false'
        responseData['mesage'] = 'Wrong Method'
        return JsonResponse(responseData, status=400)

def dogsGet(request):

    if request.method == 'POST':

        try:
            json_object = json.loads(request.body)
            try:
                one_entry = Dogs.objects.get(id=json_object["dog_id"])
            except:
                responseData = {}
                responseData['success'] = 'false'
                responseData['message'] = 'The dog_id its not valid'
                return JsonResponse(responseData, status=400)
            responseData = {}
            responseData['success'] = 'true'
            responseData['data'] = {}
            responseData['data']['name'] = one_entry.name
            responseData['data']['size'] = one_entry.size
            responseData['data']['color'] = one_entry.color
            responseData['data']['type_id'] = one_entry.type_id

            return JsonResponse(responseData, status=200)
        except ValueError as e:
            responseData = {}
            responseData['success'] = 'false'
            responseData['data'] = 'Invalid Json'
            return JsonResponse(responseData, status=400)
    else:

        responseData = {}
        responseData['success'] = 'false'
        responseData['mesage'] = 'Wrong Method'
        return JsonResponse(responseData, status=400)

def dogsGetId(request, dogid):

    if request.method == 'GET':

        try:
            one_entry = Dogs.objects.get(id=dogid)
        except:
            responseData = {}
            responseData['success'] = 'false'
            responseData['message'] = 'The dog_id its not valid'
            return JsonResponse(responseData, status=400)

        responseData = {}
        responseData['success'] = 'true'
        responseData['data'] = {}
        responseData['data']['name'] = one_entry.name
        responseData['data']['size'] = one_entry.size
        responseData['data']['color'] = one_entry.color
        responseData['data']['type_id'] = one_entry.type_id

        return JsonResponse(responseData, status=200)

    else:

        responseData = {}
        responseData['success'] = 'false'
        responseData['mesage'] = 'Wrong Method'
        return JsonResponse(responseData, status=400)

def dogsUpdate(request,dogid):

    if request.method == 'POST':
        try:
            one_entry = Dogs.objects.get(id=dogid)
        except:
            responseData = {}
            responseData['success'] = 'false'
            responseData['message'] = 'The dog_id its not valid'
            return JsonResponse(responseData, status=400)
        try:
            json_object = json.loads(request.body)
            contador = 0
            #AQUI VA EL CODIGO DEL UPDATE
            try:
                value = json_object["dog_name"]
                Dogs.objects.filter(id=dogid).update(name=json_object["dog_name"])
                contador = contador + 1
            except KeyError:
                responseData = {}

            try:
                value = json_object["dog_size"]
                Dogs.objects.filter(id=dogid).update(size=json_object["dog_size"])
                contador = contador + 1
            except KeyError:
                responseData = {}

            try:
                value = json_object["dog_color"]
                Dogs.objects.filter(id=dogid).update(color=json_object["dog_color"])
                contador = contador + 1
            except KeyError:
                responseData = {}

            try:
                value = json_object["dog_type"]
                Dogs.objects.filter(id=dogid).update(type_id=json_object["dog_type"])
                contador = contador + 1
            except KeyError:
                responseData = {}

            if contador == 0:
                responseData = {}
                responseData['success'] = 'false'
                responseData['message'] = 'Nada por actualizar'
                return JsonResponse(responseData, status=400)
            else:
                responseData = {}
                responseData['success'] = 'true'
                responseData['message'] = 'Datos actualizados'
                return JsonResponse(responseData, status=200)

        except ValueError as e:
            responseData = {}
            responseData['success'] = 'false'
            responseData['data'] = 'Invalid Json'
            return JsonResponse(responseData, status=400)

    else:

        responseData = {}
        responseData['success'] = 'false'
        responseData['mesage'] = 'Wrong Method'
        return JsonResponse(responseData, status=400)

def types(request):

    if request.method == 'GET':

        responseData = {}
        responseData['success'] = 'true'
        responseData['data'] = list(Types.objects.all().values())
        return JsonResponse(responseData, status=200)

    else:

        responseData = {}
        responseData['success'] = 'false'
        responseData['mesage'] = 'Wrong Method'
        return JsonResponse(responseData, status=400)

# videogames

UIAPI/app/firstapp/templates/add.html
{% include "header.html" %}

    

<h1 class="display-4" style="text-align: center;"><font style="vertical-align: inherit">AGREGAR VIDEOJUEGO </font></h1>
    
        
        <form role="form" action="{% url 'firstapp:videogamesAdd' %}" method="POST" > 
            <div class="card-body">
                <div class="form-group">
            {% csrf_token %}
            {{ form.as_p }} <!--el (.as_p) es para dar espacios entre cada input (es como un <br>)-->
                
                
            <input type="submit" class="btn btn-block btn-success btn-lg" value = "agregar" id="idbutton">               
                </div>
            </div>
        </form>
       

    <br>
   
      



  

{% include "footer.html" %}

UIAPI/app/firstapp/templates/clase.html
{% include "header.html" %}



  <h1 class="display-4" style="text-align: center;"><font style="vertical-align: inherit">API DE VIDEOJUEGOS </font></h1>


  
<div class="card-header" style="width:100%; height:auto; padding:20px">


 


 
  


  <div class="bg-gray-dark color-palette">

    <div class="card-header">
      <h3 class="card-title">Lista de resultados</h3>
    </div>

  <div class="card-body table-responsive p-0">
  <table class="table table-hover">
    <tr>
    
      <td><strong>id</strong></td>
      <td><strong>nombre</strong></td>
      <td><strong>genero</strong></td>
      <td><strong>Opciones</strong></td>
    </tr>
    {% for obj in videogames.data %}
      <tr>
      
        <td>{{ obj.id }}</td>
        <td>{{ obj.name }}</td>
        <td>{{ obj.genre }}</td>
        <td>
        <a href="{% url 'firstapp:update' obj.id %}" class="btn btn-block btn-primary" >Editar

        </a> <a href="{% url 'firstapp:delete' obj.id obj.name %}" class="btn btn-block btn-danger btn-lg" >Eliminar</a></td>

        


        <script>

        </script>
     


      </tr>
    {% endfor %}
  </table>
</div>


<a href="{% url 'firstapp:add' %}" class="btn btn-block btn-outline-secondary btn-lg">Agregar juegos</a>
</div>



  


</div>

{% include "footer.html" %}

UIAPI/app/firstapp/templates/delete.html
{% include "header.html" %}

<form action="{% url 'firstapp:videogamesdelete' videogameid %}" method="POST">  
    {% csrf_token %}
    
   
    <div class="alert alert-warning alert-dismissible">

        <a class="close" data-dismiss="alert" aria-hidden="true" href="{% url 'firstapp:vista' %}" id="returndelete">×</a>
        <h5><i class="icon fas fa-ban"></i> ¡Alerta!</h5>
        <h1>¿Estas seguro de querer eliminar {{ videogame }}?</h1>
    
        <input type="submit" class="btn btn-block btn-outline-danger btn-lg" value = "Si, estoy seguro" id="confirmdelete"> 
    
        
      </div>

</form>

<br>










{% include "footer.html" %}

UIAPI/app/firstapp/templates/dos.html
{% include "header.html" %}

Segunda Vista

{% include "footer.html" %}

UIAPI/app/firstapp/templates/editar.html
{% include "header.html" %}

<h1 class="display-4" style="text-align: center;"><font style="vertical-align: inherit">EDITAR VIDEOJUEGO</font></h1>
    
        
        <form role="form" method="POST" > <!-- En este caso la etiqueta <form> no lleva el atributo 'action="" ' ya que en views.py estoy trabajando con una sola función que es "editar", no como eliminar y agregar que me mandan a una función que solo es el html y del html me manda  a la función que elimina (teamsdelete) o agrega (teamsAdd) -->
            {% csrf_token %}
            {{ form.as_p }} <!--el (.as_p) es para dar espacios entre cada input (es como un <br>)-->
                
                
            <input type="submit" class="btn btn-block btn-success btn-lg" value = "EDITAR" id="button">               
        </form>
       

    <br>
    



{% include "footer.html" %}

UIAPI/app/firstapp/templates/footer.html
</body>



<footer class="bg-navy color-palette" style="position: fixed; left: 0; width: 100%; bottom:0;">
    <div class="float-right d-none d-sm-block">
      <b>Version</b> 1.0.0
    </div>
    <strong>Copyright © 2000-2021 <a href="http://adminlte.io">unimodelo.edu.mx</a>.</strong> All rights
    reserved.
</footer>

</html>

UIAPI/app/firstapp/templates/header.html
{% load static %}
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <script src="https://cdn.jsdelivr.net/npm/admin-lte@3.1/dist/js/adminlte.min.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/admin-lte@3.1/dist/css/adminlte.min.css">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
    <title>{{ title }}</title>
    <script src="{% static 'scripts.js' %}"></script>

</head>

<body class="bg-navy color-palette" style="height: auto;" >



   
    <nav class="navbar navbar-expand navbar-primary navbar-dark">
        <!-- Left navbar links -->
        <ul class="navbar-nav navbar-primary">
          <li class="nav-item d-none d-sm-inline-block">
            <a href="{% url 'firstapp:vista' %}" class="nav-link"><font style="vertical-align: inherit">INICIO</font></a>
          </li>
          
        </ul>

       
      </nav>